### ISSUE TITLE
Crashing when declared and run

### ISSUE THREAD

**Issue by hrtze** [fivdi/i2c-bus#107]
I tried using this and it just caused my node file to crash and threw this(the /path/to/project/folder is just the project folder, it would've been more confusing otherwise):

/path/to/project/folder/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: /path/to/project/folder/node_modules/i2c-bus/build/Release/i2c.node: invalid ELF header
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1167:18)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at bindings (/path/to/project/folder/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/pi/Desktop/DMX/node_modules/i2c-bus/i2c-bus.js:4:32)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32) {
  code: 'ERR_DLOPEN_FAILED'
}

any ideas? I don't really know where to go with this.

**Comment by hrtze** [comment]
That was totally why, I was doing the node project coding stuff on my mac and git fetching the repo on my rpi. I just uninstalled and reinstalled the lib on my raspberry pi and it works like a charm. Thanks so much for responding and helping me out!
